<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="INL-7RFXWF2"><DocLocation><![CDATA[C:\latestScript\Hybrid-Framework\TestScript\MainScript]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[MainScript]]></DName>
<Res><![CDATA[Res22]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Login [Login]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[6/15/2017 - 15:47:42]]></Time>
<TimeTick>1497521862</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Details>
<Time><![CDATA[6/15/2017 - 15:47:42]]></Time>
<TimeTick>1497521862</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/15/2017 - 15:48:08]]></Time>
<TimeTick>1497521888</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/15/2017 - 15:48:08]]></Time>
<TimeTick>1497521888</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Login | Salesforce.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:48:08]]></Time>
<TimeTick>1497521888</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Login | Salesforce.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["manjunath.patil@cgi.com"]]></Details>
<Time><![CDATA[6/15/2017 - 15:48:13]]></Time>
<TimeTick>1497521893</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="20" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[pw.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Locked@24$"]]></Details>
<Time><![CDATA[6/15/2017 - 15:48:14]]></Time>
<TimeTick>1497521894</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[pw.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Log In to Sandbox ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:48:16]]></Time>
<TimeTick>1497521896</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[[ Log In to Sandbox ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="16" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Login | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Accounts | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Login page]]></Obj>
<Details ><![CDATA[Home page is shown successfully]]></Details>
<Time><![CDATA[6/15/2017 - 15:48:45]]></Time>
<TimeTick>1497521925</TimeTick>
<NodeArgs eType="User" icon="11" nRep="28" status="Passed" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Login page]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/15/2017 - 15:47:41" eTime="6/15/2017 - 15:48:45" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Passed" >
<Disp><![CDATA[Login [Login] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T15">
<AName><![CDATA[AccountCreationBillTo [AccountCreationBillTo]]]></AName>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Verifications]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["AccountName"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (184 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>html tag=SPAN<br>acc_name=<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (184 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=SPAN<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 175 matches)</SPAN><br>class=uiOutputText<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>innertext=AccName_Automation_Billto_106<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="34" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA["AccountName"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="33" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Verifications]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="32" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Accounts | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Account Name Verification]]></Obj>
<Details ><![CDATA[Account:  Verification Failure]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<NodeArgs eType="User" icon="11" nRep="35" status="Failed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Account Name Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[SubChannel Verification]]></Obj>
<Details ><![CDATA[SubChannel:  Verification Failure]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<NodeArgs eType="User" icon="11" nRep="37" status="Failed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[SubChannel Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[Channel Verification]]></Obj>
<Details ><![CDATA[Channel:  Verification Successful]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<NodeArgs eType="User" icon="11" nRep="39" status="Passed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Channel Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Streetname Verification]]></Obj>
<Details ><![CDATA[Street:  Verification Successful]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<NodeArgs eType="User" icon="11" nRep="41" status="Passed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Streetname Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Verifications]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["AccountName"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (184 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>html tag=SPAN<br>acc_name=<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (184 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=SPAN<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 175 matches)</SPAN><br>class=uiOutputText<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>innertext=AccName_Automation_Billto_106<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="45" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA["AccountName"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="44" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Verifications]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="43" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Accounts | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[Account Name Verification]]></Obj>
<Details ><![CDATA[Account:  Verification Failure]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:06]]></Time>
<TimeTick>1497521946</TimeTick>
<NodeArgs eType="User" icon="11" nRep="46" status="Failed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Account Name Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[SubChannel Verification]]></Obj>
<Details ><![CDATA[SubChannel:  Verification Failure]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:07]]></Time>
<TimeTick>1497521947</TimeTick>
<NodeArgs eType="User" icon="11" nRep="48" status="Failed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[SubChannel Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Channel Verification]]></Obj>
<Details ><![CDATA[Channel:  Verification Successful]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:07]]></Time>
<TimeTick>1497521947</TimeTick>
<NodeArgs eType="User" icon="11" nRep="50" status="Passed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Channel Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Streetname Verification]]></Obj>
<Details ><![CDATA[Street:  Verification Successful]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:07]]></Time>
<TimeTick>1497521947</TimeTick>
<NodeArgs eType="User" icon="11" nRep="52" status="Passed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Streetname Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:28]]></Time>
<TimeTick>1497521968</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:28]]></Time>
<TimeTick>1497521968</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA["Accounts | Salesforce"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:28]]></Time>
<TimeTick>1497521968</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" status="Warning" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA["Accounts | Salesforce"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA["Accounts | Salesforce"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>title=Accounts \| Salesforce.*<br>micclass=Page<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Page<br>]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:28]]></Time>
<TimeTick>1497521968</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="57" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA["Accounts | Salesforce"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[lnk_MainWinAccounts.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:28]]></Time>
<TimeTick>1497521968</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="59" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[lnk_MainWinAccounts.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[lnk_AccountNew.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:32]]></Time>
<TimeTick>1497521972</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="62" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[lnk_AccountNew.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Bill To.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:35]]></Time>
<TimeTick>1497521975</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="67" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Bill To.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Next.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:35]]></Time>
<TimeTick>1497521975</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="70" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Next.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[wnd_CreateAccountBillTo]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:38]]></Time>
<TimeTick>1497521978</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA["txt_AccNameBillto"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (22 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=text<br>name=WebEdit<br>micclass=WebEdit<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (22 objects found)&nbsp;</FONT></u><br>
type=text<br>micclass=WebEdit<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=WebEdit<SPAN class=passed> (Used</SPAN>, 22 matches)</SPAN><br>html id=2599:0<SPAN class=Failed> (Skipped)</SPAN><br>max length=524288<SPAN class=passed> (Used</SPAN>, 6 matches)</SPAN><br>default value=<SPAN class=passed> (Used</SPAN>, 6 matches)</SPAN><br>class=input uiInput uiInputText uiInput--default uiInput--input<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>rows=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:38]]></Time>
<TimeTick>1497521978</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="75" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA["txt_AccNameBillto"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[txt_AccNameBillto.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["AccName_Automation_Billto_113"]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:38]]></Time>
<TimeTick>1497521978</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="76" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[txt_AccNameBillto.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA["lst_BusinessUnit"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (3 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>name=select<br>micclass=WebList<br>html tag=SELECT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=WebList<br>html tag=SELECT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=select<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>html id=8650:0<SPAN class=Failed> (Skipped)</SPAN><br>class=select<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>default value=<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>items count=2<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible items=5<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:42]]></Time>
<TimeTick>1497521982</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="79" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA["lst_BusinessUnit"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[lst_BusinessUnit.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["PLNA"]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:42]]></Time>
<TimeTick>1497521982</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="80" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[lst_BusinessUnit.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[btn_Channel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:43]]></Time>
<TimeTick>1497521983</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="83" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[btn_Channel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="74" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[wnd_CreateAccountBillTo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[elm_ChannelOptionlist]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:46]]></Time>
<TimeTick>1497521986</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[lnk_ChannerlOptions.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:46]]></Time>
<TimeTick>1497521986</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="87" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[lnk_ChannerlOptions.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="86" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[elm_ChannelOptionlist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[wnd_CreateAccountBillTo]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:48]]></Time>
<TimeTick>1497521988</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[txt_Phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["111-111-1122"]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:48]]></Time>
<TimeTick>1497521988</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="91" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[txt_Phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[txt_Fax.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["221-111-2222"]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:48]]></Time>
<TimeTick>1497521988</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="94" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[txt_Fax.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[btn_Sub Channel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:49]]></Time>
<TimeTick>1497521989</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="97" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[btn_Sub Channel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="90" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[wnd_CreateAccountBillTo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[elm_SubChannelOptionlist]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:50]]></Time>
<TimeTick>1497521990</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[lnk_listoptions.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:50]]></Time>
<TimeTick>1497521990</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="101" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[lnk_listoptions.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="100" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[elm_SubChannelOptionlist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[wnd_CreateAccountBillTo]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:51]]></Time>
<TimeTick>1497521991</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[btn_Commercial Relation.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:51]]></Time>
<TimeTick>1497521991</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="105" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[btn_Commercial Relation.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="104" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[wnd_CreateAccountBillTo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[elm_CommercialRelationlistblank]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:55]]></Time>
<TimeTick>1497521995</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[lnk_listoptions.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 15:49:55]]></Time>
<TimeTick>1497521995</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="109" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[lnk_listoptions.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="108" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[elm_CommercialRelationlistblank]]></Disp>