<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="INL-7RFXWF2"><DocLocation><![CDATA[C:\latestScript\Hybrid-Framework\TestScript\MainScript]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[MainScript]]></DName>
<Res><![CDATA[Res13]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Login [Login]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[6/15/2017 - 12:33:34]]></Time>
<TimeTick>1497510214</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Details>
<Time><![CDATA[6/15/2017 - 12:33:34]]></Time>
<TimeTick>1497510214</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/15/2017 - 12:33:57]]></Time>
<TimeTick>1497510237</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/15/2017 - 12:33:57]]></Time>
<TimeTick>1497510237</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Login | Salesforce.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 12:33:57]]></Time>
<TimeTick>1497510237</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Login | Salesforce.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["manjunath.patil@cgi.com"]]></Details>
<Time><![CDATA[6/15/2017 - 12:33:57]]></Time>
<TimeTick>1497510237</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="20" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[pw.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Locked@24$"]]></Details>
<Time><![CDATA[6/15/2017 - 12:33:58]]></Time>
<TimeTick>1497510238</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[pw.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Log In to Sandbox ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 12:34:00]]></Time>
<TimeTick>1497510240</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[[ Log In to Sandbox ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="16" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Login | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Accounts | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Login page]]></Obj>
<Details ><![CDATA[Home page is not shown]]></Details>
<Time><![CDATA[6/15/2017 - 12:34:35]]></Time>
<TimeTick>1497510275</TimeTick>
<NodeArgs eType="User" icon="11" nRep="28" status="Failed" Source="Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Login page]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/15/2017 - 12:33:33" eTime="6/15/2017 - 12:34:35" passed="1" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Failed" >
<Disp><![CDATA[Login [Login] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T15">
<AName><![CDATA[AccountCreationBillTo [AccountCreationBillTo]]]></AName>
<Step rID="T16">
<Obj ><![CDATA[Account Name Verification]]></Obj>
<Details ><![CDATA[Account Name Verification Successful]]></Details>
<Time><![CDATA[6/15/2017 - 12:34:57]]></Time>
<TimeTick>1497510297</TimeTick>
<NodeArgs eType="User" icon="11" nRep="32" status="Passed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Account Name Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Account Name Verification]]></Obj>
<Details ><![CDATA[Account Name Verification Successful]]></Details>
<Time><![CDATA[6/15/2017 - 12:35:17]]></Time>
<TimeTick>1497510317</TimeTick>
<NodeArgs eType="User" icon="11" nRep="34" status="Passed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="-1" >
<Disp><![CDATA[Account Name Verification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/15/2017 - 12:36:07]]></Time>
<TimeTick>1497510367</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/15/2017 - 12:36:07]]></Time>
<TimeTick>1497510367</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["lnk_MainWinAccounts"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[6/15/2017 - 12:36:07]]></Time>
<TimeTick>1497510367</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="39" status="Warning" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="43" >
<Disp><![CDATA["lnk_MainWinAccounts"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["lnk_MainWinAccounts"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=Accounts<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br>]]></Details>
<Time><![CDATA[6/15/2017 - 12:36:07]]></Time>
<TimeTick>1497510367</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="40" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="43" >
<Disp><![CDATA["lnk_MainWinAccounts"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[lnk_MainWinAccounts.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 12:36:07]]></Time>
<TimeTick>1497510367</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="41" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="43" >
<Disp><![CDATA[lnk_MainWinAccounts.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[lnk_AccountNew]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"lnk_AccountNew"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[6/15/2017 - 12:36:56]]></Time>
<TimeTick>1497510416</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[lnk_AccountNew]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Link<br>Html Tag = A<br>_xpath = //DIV[5]/DIV[1]/SECTION[1]/DIV[2]/DIV[1]/DIV[1]/DIV[1]/DIV[@role="banner"][1]/DIV[1]/DIV[2]/UL[1]/LI[1]/A[1]<br>|Visible = -1<br>Text = New<br>Name = New<br>Html Id = <br>Href = javascript:void(0);<br>DHTML Class = forceActionLink<br>]]></Details>
<Time><![CDATA[6/15/2017 - 12:36:56]]></Time>
<TimeTick>1497510416</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="57" status="Warning" nType="Description" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="43" >
<Disp><![CDATA[lnk_AccountNew]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="12" nRep="56" status="Failed" nType="Run Error" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="43" >
<Disp><![CDATA[lnk_AccountNew]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="38" status="Failed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="43" >
<Disp><![CDATA[Accounts | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="37" status="Failed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="43" >
<Disp><![CDATA[Accounts | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/15/2017 - 12:36:56]]></Time>
<TimeTick>1497510416</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;lnk_AccountNew&quot; (of class Link).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (99): &quot;Browser(&quot;Accounts | Salesforce&quot;).Page(&quot;Accounts | Salesforce&quot;).Link(&quot;lnk_AccountNew&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[6/15/2017 - 12:36:56]]></Time>
<TimeTick>1497510416</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="59" status="Failed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="98" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[6/15/2017 - 12:38:14]]></Time>
<TimeTick>1497510494</TimeTick>
<NodeArgs eType="General" icon="15" nRep="60" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="58" status="Failed" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="98" >
<Disp><![CDATA[Accounts | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/15/2017 - 12:34:36" eTime="6/15/2017 - 12:38:14" passed="2" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="30" status="Failed" >
<Disp><![CDATA[AccountCreationBillTo [AccountCreationBillTo] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="6/15/2017 - 12:33:33" eTime="6/15/2017 - 12:38:14" passed="0" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Param1]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[Param2]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[MainScript Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="6/15/2017 - 12:33:32" eTime="6/15/2017 - 12:38:14" passed="3" failed="3" warnings="2" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test MainScript Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>