<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="INL-7RFXWF2"><DocLocation><![CDATA[C:\latestScript\Hybrid-Framework\TestScript\MainScript]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[MainScript]]></DName>
<Res><![CDATA[Res29]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Login [Login]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[6/15/2017 - 16:29:35]]></Time>
<TimeTick>1497524375</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Details>
<Time><![CDATA[6/15/2017 - 16:29:35]]></Time>
<TimeTick>1497524375</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Login [Login]" SourceLine="54" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Login [Login]" SourceLine="54" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/15/2017 - 16:29:52]]></Time>
<TimeTick>1497524392</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/15/2017 - 16:29:52]]></Time>
<TimeTick>1497524392</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Login | Salesforce.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:29:52]]></Time>
<TimeTick>1497524392</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" Source="Login [Login]" SourceLine="57" >
<Disp><![CDATA[Login | Salesforce.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["manjunath.patil@cgi.com"]]></Details>
<Time><![CDATA[6/15/2017 - 16:29:58]]></Time>
<TimeTick>1497524398</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="20" Source="Login [Login]" SourceLine="59" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[pw.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Locked@24$"]]></Details>
<Time><![CDATA[6/15/2017 - 16:29:58]]></Time>
<TimeTick>1497524398</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="Login [Login]" SourceLine="60" >
<Disp><![CDATA[pw.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Log In to Sandbox ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:30:00]]></Time>
<TimeTick>1497524400</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" Source="Login [Login]" SourceLine="65" >
<Disp><![CDATA[[ Log In to Sandbox ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="16" Source="Login [Login]" SourceLine="57" >
<Disp><![CDATA[Login | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Login [Login]" SourceLine="57" >
<Disp><![CDATA[Accounts | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Login page]]></Obj>
<Details ><![CDATA[Home page is shown successfully]]></Details>
<Time><![CDATA[6/15/2017 - 16:30:19]]></Time>
<TimeTick>1497524419</TimeTick>
<NodeArgs eType="User" icon="11" nRep="28" status="Passed" Source="Login [Login]" SourceLine="71" >
<Disp><![CDATA[Login page]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/15/2017 - 16:29:34" eTime="6/15/2017 - 16:30:19" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Passed" >
<Disp><![CDATA[Login [Login] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T15">
<AName><![CDATA[AccountCreationBillTo [AccountCreationBillTo]]]></AName>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/15/2017 - 16:30:42]]></Time>
<TimeTick>1497524442</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/15/2017 - 16:30:42]]></Time>
<TimeTick>1497524442</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["Accounts | Salesforce"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[6/15/2017 - 16:30:42]]></Time>
<TimeTick>1497524442</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" status="Warning" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="95" >
<Disp><![CDATA["Accounts | Salesforce"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["Accounts | Salesforce"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>title=Accounts \| Salesforce.*<br>micclass=Page<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Page<br>]]></Details>
<Time><![CDATA[6/15/2017 - 16:30:42]]></Time>
<TimeTick>1497524442</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="35" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="95" >
<Disp><![CDATA["Accounts | Salesforce"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Accounts | Salesforce.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:30:42]]></Time>
<TimeTick>1497524442</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="37" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="95" >
<Disp><![CDATA[Accounts | Salesforce.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["Accounts | Salesforce"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:03]]></Time>
<TimeTick>1497524463</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" status="Warning" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="96" >
<Disp><![CDATA["Accounts | Salesforce"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["Accounts | Salesforce"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>title=Accounts \| Salesforce.*<br>micclass=Page<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Page<br>]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:03]]></Time>
<TimeTick>1497524463</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="40" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="96" >
<Disp><![CDATA["Accounts | Salesforce"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[lnk_MainWinAccounts.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:03]]></Time>
<TimeTick>1497524463</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="42" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="96" >
<Disp><![CDATA[lnk_MainWinAccounts.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[lnk_AccountNew.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:06]]></Time>
<TimeTick>1497524466</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="45" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="98" >
<Disp><![CDATA[lnk_AccountNew.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Bill To.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:08]]></Time>
<TimeTick>1497524468</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="49" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="101" >
<Disp><![CDATA[Bill To.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Next.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:09]]></Time>
<TimeTick>1497524469</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="105" >
<Disp><![CDATA[Next.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[wnd_CreateAccountBillTo]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:11]]></Time>
<TimeTick>1497524471</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA["txt_AccNameBillto"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (22 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=text<br>name=WebEdit<br>micclass=WebEdit<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (22 objects found)&nbsp;</FONT></u><br>
type=text<br>micclass=WebEdit<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=WebEdit<SPAN class=passed> (Used</SPAN>, 22 matches)</SPAN><br>html id=2599:0<SPAN class=Failed> (Skipped)</SPAN><br>max length=524288<SPAN class=passed> (Used</SPAN>, 6 matches)</SPAN><br>default value=<SPAN class=passed> (Used</SPAN>, 6 matches)</SPAN><br>class=input uiInput uiInputText uiInput--default uiInput--input<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>rows=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:11]]></Time>
<TimeTick>1497524471</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="56" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="107" >
<Disp><![CDATA["txt_AccNameBillto"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[txt_AccNameBillto.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["AccName_Automation_Billto_118"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:12]]></Time>
<TimeTick>1497524472</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="57" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="107" >
<Disp><![CDATA[txt_AccNameBillto.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA["lst_BusinessUnit"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (3 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>name=select<br>micclass=WebList<br>html tag=SELECT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=WebList<br>html tag=SELECT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=select<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>html id=8650:0<SPAN class=Failed> (Skipped)</SPAN><br>class=select<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>default value=<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>items count=2<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible items=5<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:16]]></Time>
<TimeTick>1497524476</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="60" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="111" >
<Disp><![CDATA["lst_BusinessUnit"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[lst_BusinessUnit.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["PLNA"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:16]]></Time>
<TimeTick>1497524476</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="61" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="111" >
<Disp><![CDATA[lst_BusinessUnit.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[btn_Channel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:16]]></Time>
<TimeTick>1497524476</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="64" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="114" >
<Disp><![CDATA[btn_Channel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="55" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="107" >
<Disp><![CDATA[wnd_CreateAccountBillTo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[elm_ChannelOptionlist]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:20]]></Time>
<TimeTick>1497524480</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[lnk_ChannerlOptions.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:20]]></Time>
<TimeTick>1497524480</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="68" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="118" >
<Disp><![CDATA[lnk_ChannerlOptions.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="67" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="118" >
<Disp><![CDATA[elm_ChannelOptionlist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[wnd_CreateAccountBillTo]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:22]]></Time>
<TimeTick>1497524482</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[txt_Phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["111-111-1122"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:22]]></Time>
<TimeTick>1497524482</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="123" >
<Disp><![CDATA[txt_Phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[txt_Fax.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["221-111-2222"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:22]]></Time>
<TimeTick>1497524482</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="75" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="125" >
<Disp><![CDATA[txt_Fax.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[btn_Sub Channel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:23]]></Time>
<TimeTick>1497524483</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="78" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="128" >
<Disp><![CDATA[btn_Sub Channel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="71" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="123" >
<Disp><![CDATA[wnd_CreateAccountBillTo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[elm_SubChannelOptionlist]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:24]]></Time>
<TimeTick>1497524484</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[lnk_listoptions.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:24]]></Time>
<TimeTick>1497524484</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="82" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="132" >
<Disp><![CDATA[lnk_listoptions.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="81" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="132" >
<Disp><![CDATA[elm_SubChannelOptionlist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[wnd_CreateAccountBillTo]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:25]]></Time>
<TimeTick>1497524485</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[btn_Commercial Relation.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:25]]></Time>
<TimeTick>1497524485</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="86" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="136" >
<Disp><![CDATA[btn_Commercial Relation.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="85" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="136" >
<Disp><![CDATA[wnd_CreateAccountBillTo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[elm_CommercialRelationlistblank]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:29]]></Time>
<TimeTick>1497524489</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[lnk_listoptions.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:29]]></Time>
<TimeTick>1497524489</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="90" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="140" >
<Disp><![CDATA[lnk_listoptions.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="89" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="140" >
<Disp><![CDATA[elm_CommercialRelationlistblank]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[wnd_CreateAccountBillTo]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:30]]></Time>
<TimeTick>1497524490</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[txt_WebSite.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["http://Michelintesting.com"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:30]]></Time>
<TimeTick>1497524490</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="94" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="141" >
<Disp><![CDATA[txt_WebSite.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[txt_BillingStreet.Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:32]]></Time>
<TimeTick>1497524492</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="95" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="154" >
<Disp><![CDATA[txt_BillingStreet.Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[txt_BillingStreet.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1 Parkway South"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:33]]></Time>
<TimeTick>1497524493</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="99" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="155" >
<Disp><![CDATA[txt_BillingStreet.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[txt_BillingCity.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Greenville"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:33]]></Time>
<TimeTick>1497524493</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="102" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="156" >
<Disp><![CDATA[txt_BillingCity.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[txt_BillingState.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SC"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:34]]></Time>
<TimeTick>1497524494</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="105" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="157" >
<Disp><![CDATA[txt_BillingState.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[txt_Billingzip.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["29676"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:34]]></Time>
<TimeTick>1497524494</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="108" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="158" >
<Disp><![CDATA[txt_Billingzip.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[txt_BillingCountry.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["US"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:35]]></Time>
<TimeTick>1497524495</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="111" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="159" >
<Disp><![CDATA[txt_BillingCountry.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[txt_ShippingStreet.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1 Parkway South"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:36]]></Time>
<TimeTick>1497524496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="114" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="163" >
<Disp><![CDATA[txt_ShippingStreet.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[txt_ShippingCity.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Greenville"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:36]]></Time>
<TimeTick>1497524496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="117" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="164" >
<Disp><![CDATA[txt_ShippingCity.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[txt_Shippingstate.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SC"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:36]]></Time>
<TimeTick>1497524496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="120" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="165" >
<Disp><![CDATA[txt_Shippingstate.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[txt_Shippingzip.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["29676"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:37]]></Time>
<TimeTick>1497524497</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="123" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="166" >
<Disp><![CDATA[txt_Shippingzip.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[txt_ShippingCoutry.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["US"]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:37]]></Time>
<TimeTick>1497524497</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="126" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="167" >
<Disp><![CDATA[txt_ShippingCoutry.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[btn_Credit Rating.Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:39]]></Time>
<TimeTick>1497524499</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="127" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="174" >
<Disp><![CDATA[btn_Credit Rating.Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[btn_Credit Rating.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/15/2017 - 16:31:40]]></Time>
<TimeTick>1497524500</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="131" Source="AccountCreationBillTo [AccountCreationBillTo]" SourceLine="175" >